trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  dockerId: blueseph28
  imageName: android-build-environment
  pswd: $(dpswd)

steps:
- script: docker login -u $(dockerId) -p $(pswd)
  displayName: 'Login to DockerHub'

- script: |
    docker build -t $(dockerId)/$(imageName) .
    docker push $(dockerId)/$(imageName)
  displayName: 'build and upload the image'